version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:80"
    environment:
      - MONGO_HOST=172.17.0.3
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
